# Generated by Django 5.2.7 on 2025-11-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_genre_game_genre_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mainApp.game'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
