# Generated by Django 5.2.7 on 2025-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
