# Generated by Django 5.2.7 on 2025-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
