# Generated by Django 5.2.7 on 2025-11-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_status',
            field=models.CharField(default='WIP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
