# Generated by Django 5.2.7 on 2025-11-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_game_current_status_game_platforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='mainApp.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='released_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
